# Generated by Django 4.0.3 on 2022-04-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('need_shipment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('IN_PROCESS', 'In process'), ('PENDING', 'Pending'), ('CANCEL', 'Cancel')], default='PAID', max_length=24)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('DEBIT_CARD', 'Debit card'), ('OTHER', 'Other')], default='CARD', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ON_WAY', 'On way'), ('DIGITAL', 'Digital'), ('IN_PROCESS', 'In process')], default='IN_PROCESS', max_length=24)),
            ],
        ),
    ]
