# Generated by Django 4.0.3 on 2022-05-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('need_shipment', models.BooleanField(default=False)),
                ('albums', models.TextField(max_length=255, null=True)),
                ('albums_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.albums')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('IN_PROCESS', 'In process'), ('PENDING', 'Pending'), ('CANCEL', 'Cancel')], default='PAID', max_length=24)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('DEBIT_CARD', 'Debit card'), ('OTHER', 'Other')], default='CARD', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ON_WAY', 'On way'), ('DIGITAL', 'Digital'), ('IN_PROCESS', 'In process')], default='IN_PROCESS', max_length=24)),
                ('order', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='market.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.payments'),
        ),
        migrations.AddField(
            model_name='orders',
            name='songs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.songs'),
        ),
    ]
