# Generated by Django 4.0.3 on 2022-05-07 01:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual'), ('BOTH', 'Both')], default='BOTH', max_length=24)),
                ('virtual_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('physical_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.TextField(default=0)),
                ('file', models.TextField(default=0)),
                ('duration', models.DurationField()),
                ('stock', models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('nationality', models.TextField(max_length=225)),
                ('image', models.TextField(default=0)),
                ('albums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.albums')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('duration', models.DurationField()),
                ('image', models.TextField(default=0)),
                ('is_single', models.BooleanField(default=False)),
                ('file', models.TextField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.authors')),
            ],
        ),
        migrations.AddField(
            model_name='albums',
            name='genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.genres'),
        ),
    ]
